### ISSUE TITLE
Example

### ISSUE THREAD

**Issue by Cezikos** [mac-developer/openid-wargaming#3]
Can you make a fully working example with Django 2.0?

**Comment by mac-developer** [comment]
@Cezikos 
I am going to work on it.

Thanks.

**Comment by mac-developer** [comment]
@Cezikos 

I've developed an example with http.server (Python 3.6 standard library) while still working on Django example.

https://github.com/mac-developer/openid-wargaming/blob/master/example.py

**Comment by mac-developer** [comment]
@Cezikos 

Here is your Django 2.0 example:

https://github.com/mac-developer/openid-wargaming-django-example

Thank you for your suggestion ;).
